# Generated by Django 2.0.5 on 2022-07-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
